# trattandosi di un repository di esempio lascio pwd e utenza in chairo permettono a chiunque di avviare il progetto con comando "docker compose up"
# In un contesto enterprise utilizzerei un file .env escluso dal versionamento oppure un sistema di secret management come AWS Secrets Manager, 
# integrato con ECS/Fargate per evitare la presenza di credenziali nel repository.
services:

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: cloud_demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8080:8080"

    environment:
      DB_URL: jdbc:postgresql://postgres:5432/cloud_demo
      DB_USER: postgres
      DB_PASSWORD: postgres

    depends_on:
      - postgres
